[package]
name = "pathogen-worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pathogen-worker"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] } 
