# Use plugin for runtime transformations
preload = ["./src/testing/moxxy-transformer.ts"]

# Use plugin for test transformations  
[test]
preload = ["./src/testing/moxxy-transformer.ts", './src/testing/extensions.ts']
