# Use plugin for runtime transformations
preload = ["./src/testing/moxxy/transformer-plugin.ts"]

# Use plugin for test transformations  
[test]
preload = [
  "./src/testing/moxxy/transformer-plugin.ts",
  "./src/testing/extensions.ts",
  "./src/testing/moxxy/auto-reset.ts",
  "./src/testing/setup/windows-path-setup.ts"
]
