# Use plugin for runtime transformations
preload = ["./src/testing/transform-plugin.ts"]

# Use plugin for test transformations  
[test]
preload = ["./src/testing/transform-plugin.ts", './src/testing/extensions.ts']
