name: 'Setup Klep Dependencies'
description: 'Sets up Node.js, Bun, Rust, installs dependencies, and bootstraps Klep'

inputs:
  rust-components:
    description: 'Additional Rust components to install (e.g., rustfmt, clippy)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Python for universalmutator
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install universalmutator
      run: pip install universalmutator
      shell: bash

    # Cache Bun dependencies and global cache
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: ${{ inputs.rust-components }}
        cache-workspaces: src/rust
        # Enable caching and cache on failure for better cache utilization
        cache: true
        cache-on-failure: true

    # Additional Rust caching for target directory
    - name: Cache Rust target directory
      uses: actions/cache@v4
      with:
        path: src/rust/target
        key: ${{ runner.os }}-rust-target-${{ hashFiles('src/rust/**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-rust-target-

    - name: Install Node dependencies
      run: bun install --frozen-lockfile
      shell: bash

    # Cache klep bootstrap artifacts
    - name: Cache klep bootstrap
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/bin/klep
          ${{ github.workspace }}/klep
        key: ${{ runner.os }}-klep-bootstrap-${{ hashFiles('src/**', 'bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-klep-bootstrap-

    - name: Bootstrap klep
      run: bun run src/index.ts link
      shell: bash

    - name: Add klep to PATH (Unix)
      if: runner.os != 'Windows'
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Add klep to PATH (Windows)
      if: runner.os == 'Windows'
      run: echo "${{ github.workspace }}" >> $env:GITHUB_PATH
      shell: pwsh 
