[package]
name = "kleptool_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "kleptool_rust_bin"
path = "src/main.rs"

[dependencies]
wasm-bindgen = "0.2.87"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
wasm_bindgen_macro_support = "0.2.87"
paste = "1.0.14"
kleptool_macros = { path = "./macros" }

[workspace]
members = ["macros"]

[profile.release]
opt-level = 3
lto = true 