[package]
name = "gud"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
paste = "1.0.14"
lazy_static = "1.4.0"

[workspace]
resolver = "2"
members = [
  "api/ast",
  "api/astar",
  "api/common",
  "api/nn",
  "api/std",
]
