[package]
name = "kleptool_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "web_assembly"
crate-type = ["cdylib", "rlib"]
path = "web-assembly/lib.rs"

[[bin]]
name = "kleptool_rust_bin"
path = "main.rs"

[dependencies]
wasm-bindgen = "0.2.87"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
wasm_bindgen_macro_support = "0.2.87"
paste = "1.0.14"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[profile.release]
opt-level = 3
lto = true 