[package]
name = "kleptool_rust"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "kleptool_rust"

[dependencies]
wasm-bindgen = "0.2.87"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
wasm-bindgen-macro-support = "0.2.87"
paste = "1.0.14"
