name: 'Setup Development Environment'
description: 'Sets up Node.js, Rust, and project dependencies with caching'
inputs:
  install-cargo-audit:
    description: 'Whether to install cargo-audit'
    required: false
    default: 'false'
  rust-components:
    description: 'Additional Rust components to install'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: ${{ inputs.rust-components }}
        cache-workspaces: src/rust

    - name: Cache cargo binaries
      if: inputs.install-cargo-audit == 'true'
      uses: actions/cache@v4
      id: cargo-audit-cache
      with:
        path: ~/.cargo/bin/cargo-audit
        key: cargo-audit-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-audit-${{ runner.os }}-

    - name: Install cargo-audit
      if: inputs.install-cargo-audit == 'true' && steps.cargo-audit-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo install cargo-audit --locked

    - name: Install Node dependencies
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Bootstrap klep
      shell: bash
      run: npx tsx src/index.ts link

    - name: Setup PATH for klep
      shell: bash
      run: npx tsx src/index.ts ci:ensurepath
