name: 'Setup Cargo Crates'
description: 'Sets up additional Cargo crates'

inputs:
  cargo-crates:
    description: 'Additional Cargo crates to install'
    required: true
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache Cargo Crates
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: ${{ runner.os }}-cargo-crates-v0.32.7
        restore-keys: |
          ${{ runner.os }}-cargo-crates-

    - name: Install Cargo Crates
      if: steps.cache-cargo-crates.outputs.cache-hit != 'true'
      run: cargo install ${{ inputs.cargo-crates }}