name: 'Coverage'
description: 'Handles uploading and comparing coverage for a pull request'

inputs:
  operation:
    description: 'The operation to perform (upload, compare)'
    required: true
    default: 'upload'

runs:
  using: 'composite'
  steps:
    # Upload Coverage
    - name: Upload Coverage (TypeScript)
      if: inputs.operation == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: dev-typescript-coverage
        path: ./coverage/typescript/lcov.info
        retention-days: 30

    - name: Upload Coverage (Rust)
      if: inputs.operation == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: dev-rust-coverage
        path: ./coverage/rust/lcov.info
        retention-days: 30

    # Compare Coverage
    - name: Download TypeScript Base Coverage from dev
      if: inputs.operation == 'compare'
      uses: dawidd6/action-download-artifact@v3
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        name: dev-typescript-coverage
        path: ./base-coverage/typescript/
        if_no_artifact_found: warn

    - name: Download Rust Base Coverage from dev
      if: inputs.operation == 'compare'
      uses: dawidd6/action-download-artifact@v3
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        name: dev-rust-coverage
        path: ./base-coverage/rust/
        if_no_artifact_found: warn

    - name: Check if TypeScript base coverage exists
      id: check-ts-base
      run: |
        if [ -f "./base-coverage/typescript/lcov.info" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi  

    - name: Check if Rust base coverage exists
      id: check-rust-base
      run: |
        if [ -f "./base-coverage/rust/lcov.info" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Compare Coverage (TypeScript)
      if: inputs.operation == 'compare'
      uses: barecheck/code-coverage-action@v1
      with:
        lcov-file: "./coverage/typescript/lcov.info"
        base-lcov-file: "./base-coverage/typescript/lcov.info"
        minimum-ratio: 0
        send-summary-comment: true
        show-annotations: "warning"

    - name: Compare Coverage (Rust)
      if: inputs.operation == 'compare'
      uses: barecheck/code-coverage-action@v1
      with:
        lcov-file: "./coverage/rust/lcov.info"
        base-lcov-file: "./base-coverage/rust/lcov.info"
        minimum-ratio: 0
        send-summary-comment: true
        show-annotations: "warning"

    - name: Generate TypeScript Coverage Report (no baseline)
      if: steps.check-ts-base.outputs.exists == 'false'
      uses: barecheck/code-coverage-action@v1
      with:
        lcov-file: "./coverage/typescript/lcov.info"
        minimum-ratio: 0
        send-summary-comment: true
        show-annotations: "warning"
        app-name: "TypeScript (No Baseline)"

    - name: Generate Rust Coverage Report (no baseline)
      if: steps.check-rust-base.outputs.exists == 'false'
      uses: barecheck/code-coverage-action@v1
      with:
        lcov-file: "./coverage/rust/lcov.info"
        minimum-ratio: 0
        send-summary-comment: true
        show-annotations: "warning"
        app-name: "Rust (No Baseline)"