name: 'Coverage'
description: 'Handles uploading and comparing behavioral coverage for a pull request'

inputs:
  operation:
    description: 'The operation to perform (upload, compare, badge)'
    required: true
    default: 'upload'
  github_token:
    description: 'GitHub token for downloading artifacts'
    required: false
    default: ''
  barecheck_token:
    description: 'Barecheck GitHub App token for code coverage reports'
    required: false
    default: ''
  gist_id:
    description: 'GitHub Gist ID for badge storage (will be created if not provided)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Upload Behavioral Coverage
    - name: Upload Behavioral Coverage Report
      if: inputs.operation == 'upload'
      uses: actions/upload-artifact@v4
      with:
        name: dev-mutation-coverage
        path: ./pathogen-report.json
        retention-days: 30

    # Compare Behavioral Coverage
    - name: Download Base Mutation Coverage from dev
      if: inputs.operation == 'compare'
      uses: dawidd6/action-download-artifact@v10
      continue-on-error: true
      with:
        github_token: ${{ inputs.github_token }}
        branch: dev
        name: dev-mutation-coverage
        path: ./base-coverage/mutation/
        if_no_artifact_found: warn

    - name: Check if mutation base coverage exists
      id: check-mutation-base
      if: inputs.operation == 'compare'
      shell: bash
      run: |
        if [ -f "./base-coverage/mutation/pathogen-report.json" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    # Compare Mutation Results
    - name: Compare Behavioral Coverage (with baseline)
      if: inputs.operation == 'compare' && steps.check-mutation-base.outputs.exists == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: ./scripts/compare-mutation-coverage.sh "./pathogen-report.json" "./base-coverage/mutation/pathogen-report.json"

    - name: Generate Behavioral Coverage Report (no baseline)
      if: inputs.operation == 'compare' && steps.check-mutation-base.outputs.exists == 'false'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: ./scripts/compare-mutation-coverage.sh "./pathogen-report.json"

    # Badge Creation
    - name: Extract Behavioral Coverage Percentages
      if: inputs.operation == 'badge'
      id: mutation-percentages
      shell: bash
      run: ./scripts/extract-mutation-coverage.sh

    - name: Create or Update Behavioral Coverage Badges
      if: inputs.operation == 'badge'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GIST_ID: ${{ inputs.gist_id }}
        KILL_RATE: ${{ steps.mutation-percentages.outputs.kill_rate }}
        BEHAVIORAL_RATE: ${{ steps.mutation-percentages.outputs.behavioral_rate }}
      run: ./scripts/update-mutation-badges.sh
