name: Build and Test

on:
  push:
    branches: [ dev, bun-migration ]
  pull_request:
    branches: [ dev ]
    # This will run on any PR targeting dev, regardless of source branch name

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache-workspaces: src/rust

    - name: Install Node dependencies
      run: bun install --frozen-lockfile

    - name: Bootstrap klep
      run: bun run src/index.ts link

    - name: Add klep to PATH (Unix)
      if: runner.os != 'Windows'
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Add klep to PATH (Windows)
      if: runner.os == 'Windows'
      run: echo "${{ github.workspace }}" >> $env:GITHUB_PATH

    - name: Build Project
      run: klep ci:build

    - name: Test Rust
      run: |
        cd src/rust
        cargo test --workspace

    - name: Test klep CLI (Integration Tests)
      run: klep demo