name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    # This will run on any PR targeting dev, regardless of source branch name

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Integration Tests (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      # Allow jobs to run independently - don't fail all if one fails
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Klep Setup
      uses: ./.github/actions/setup-environment

    - name: Build Project
      run: klep ci:build

    - name: Test Rust
      run: |
        cd src/rust
        cargo test --workspace

    - name: Test klep CLI
      run: klep demo

    - name: Upload build artifacts (on success)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: |
          dist
          src/rust/target/release
        retention-days: 1