name: Coverage Badge

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - "**/coverage-*.svg"  # Prevents build loops when the badges are updated

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install dependencies
      run: bun install
    
    - name: Run tests with coverage
      run: bun test --coverage
    
    - name: Generate Coverage Badge (TS)
      uses: ImBIOS/lcov-coverage-badge@v1
      with:
        file: ./coverage/typescript/lcov.info
        label: 'TS Coverage'
        icon_name: typescript
        
    - name: Move TS Badge
      run: mv coverage.svg coverage-ts.svg
        
    - name: Generate Coverage Badge (Rust)
      uses: ImBIOS/lcov-coverage-badge@v1
      with:
        file: ./coverage/rust/lcov.info  
        label: 'Rust Coverage'
        icon_name: rust
        
    - name: Move Rust Badge  
      run: mv coverage.svg coverage-rust.svg
      
    - name: Commit Coverage Badges
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add coverage-ts.svg coverage-rust.svg
        git diff --staged --quiet || git commit -m "Update coverage badges [skip ci]"
        git push 