name: Test (Linux)

on:
  push:
    branches: [ dev ]
env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Klep Dependencies
      uses: ./.github/actions/setup-klep

    - name: Setup Additional Cargo Crates
      uses: ./.github/actions/setup-cargo-crates
      with:
        cargo-crates: cargo-tarpaulin

    - name: Build Project
      run: klep ci:build

    - name: Test and Generate Coverage
      run: klep coverage

    - name: Upload TypeScript Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-typescript-coverage
        path: ./coverage/typescript/lcov.info
        retention-days: 30

    - name: Upload Rust Coverage Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-rust-coverage
        path: ./coverage/rust/lcov.info
        retention-days: 30