name: Quality Control

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    # This will run on any PR targeting dev, regardless of source branch name

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  quality-control:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Klep Setup
      uses: ./.github/actions/setup-environment
      with:
        rust-components: 'rustfmt, clippy'

    - name: Run Quality Control Tasks
      run: klep ci:tidy

    - name: Run TypeScript Type Check
      run: klep ci:typecheck

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Klep Setup
      uses: ./.github/actions/setup-environment
      with:
        install-cargo-audit: 'true'

    - name: Run Security Audit
      run: klep ci:secure 