name: Quality Control

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    # This will run on any PR targeting dev, regardless of source branch name

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  quality-control:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        cache-workspaces: src/rust

    - name: Install Node dependencies
      run: yarn install --frozen-lockfile

    - name: Bootstrap klep
      run: npx tsx src/index.ts link

    - name: Add klep to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run Quality Control Tasks
      run: klep ci:tidy

    - name: Run TypeScript Type Check
      run: npx tsc --noEmit

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache-workspaces: src/rust

    - name: Install Node dependencies
      run: yarn install --frozen-lockfile

    - name: Bootstrap klep
      run: npx tsx src/index.ts link

    - name: Add klep to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run Security Audit
      run: klep ci:secure 